---
- name: Get nomad
  unarchive: src=https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm.zip dest=/usr/local/bin creates=/usr/local/bin/nomad copy=no

- name: Temporary fix for path in zip
  file: src=/usr/local/bin/linux_arm/nomad dest=/usr/local/bin/nomad state=link


- name: Ensure user
  user: name=nomad home=/var/lib/nomad shell=/bin/false createhome=no

- name: Ensure config directory
  file: path=/etc/nomad/conf.d state=directory

- name: Ensure state directories
  file: path={{ item }} owner=nomad group=nomad state=directory
  with_items:
    - /var/lib/nomad

- name: Copy launch script
  copy: src=nomad.service dest=/etc/systemd/system/nomad.service
    
- name: Enable nomad service
  service: name=nomad enabled=yes
